apiVersion: v1
kind: Service
metadata:
  name: sample-grpc-client-service
  namespace: app-ns
spec:
  selector:
    app: sample-grpc-client
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
