package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"context"
	"errors"
	"fmt"

	"github.com/shshimamo/knowledge-main/graph/generated"
	"github.com/shshimamo/knowledge-main/graph/model"
	m "github.com/shshimamo/knowledge-main/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	return r.AllService.CreateUser(ctx, &input)
}

// CreateKnowledge is the resolver for the createKnowledge field.
func (r *mutationResolver) CreateKnowledge(ctx context.Context, input *model.NewKnowledge) (*model.Knowledge, error) {
	panic(fmt.Errorf("not implemented: CreateKnowledge - createKnowledge"))
}

// UpdateKnowledge is the resolver for the updateKnowledge field.
func (r *mutationResolver) UpdateKnowledge(ctx context.Context, id string, input *model.NewKnowledge) (*model.Knowledge, error) {
	panic(fmt.Errorf("not implemented: UpdateKnowledge - updateKnowledge"))
}

// DeleteKnowledge is the resolver for the deleteKnowledge field.
func (r *mutationResolver) DeleteKnowledge(ctx context.Context, id string) (*model.DeleteKnowledgeResult, error) {
	panic(fmt.Errorf("not implemented: DeleteKnowledge - deleteKnowledge"))
}

// CurrentUser is the resolver for the currentUser field.
func (r *queryResolver) CurrentUser(ctx context.Context) (*model.User, error) {
	user, ok := m.GetCurrentUser(ctx)

	if !ok {
		return nil, errors.New("not authenticated")
	}

	return m.MapUserModelToGraph(user), nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUser - getUser"))
}

// GetKnowledge is the resolver for the getKnowledge field.
func (r *queryResolver) GetKnowledge(ctx context.Context, id string) (*model.Knowledge, error) {
	panic(fmt.Errorf("not implemented: GetKnowledge - getKnowledge"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
