apiVersion: v1
kind: Service
metadata:
  name: frontend-main-service
  namespace: app-ns
spec:
  selector:
    app: frontend-main
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
