// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteKnowledgeResult struct {
	ID      string `json:"id"`
	Success bool   `json:"success"`
}

type NewKnowledge struct {
	Title    string `json:"title"`
	Text     string `json:"text"`
	IsPublic bool   `json:"isPublic"`
}

type NewUser struct {
	Name string `json:"name"`
}

type UpdateKnowledge struct {
	Title    string `json:"title"`
	Text     string `json:"text"`
	IsPublic bool   `json:"isPublic"`
}
