// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

var TableNames = struct {
	AuthUsers      string
	GooseDBVersion string
	Tokens         string
}{
	AuthUsers:      "auth_users",
	GooseDBVersion: "goose_db_version",
	Tokens:         "tokens",
}
