// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("AuthUsers", testAuthUsers)
	t.Run("GooseDBVersions", testGooseDBVersions)
	t.Run("Tokens", testTokens)
}

func TestDelete(t *testing.T) {
	t.Run("AuthUsers", testAuthUsersDelete)
	t.Run("GooseDBVersions", testGooseDBVersionsDelete)
	t.Run("Tokens", testTokensDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("AuthUsers", testAuthUsersQueryDeleteAll)
	t.Run("GooseDBVersions", testGooseDBVersionsQueryDeleteAll)
	t.Run("Tokens", testTokensQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("AuthUsers", testAuthUsersSliceDeleteAll)
	t.Run("GooseDBVersions", testGooseDBVersionsSliceDeleteAll)
	t.Run("Tokens", testTokensSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("AuthUsers", testAuthUsersExists)
	t.Run("GooseDBVersions", testGooseDBVersionsExists)
	t.Run("Tokens", testTokensExists)
}

func TestFind(t *testing.T) {
	t.Run("AuthUsers", testAuthUsersFind)
	t.Run("GooseDBVersions", testGooseDBVersionsFind)
	t.Run("Tokens", testTokensFind)
}

func TestBind(t *testing.T) {
	t.Run("AuthUsers", testAuthUsersBind)
	t.Run("GooseDBVersions", testGooseDBVersionsBind)
	t.Run("Tokens", testTokensBind)
}

func TestOne(t *testing.T) {
	t.Run("AuthUsers", testAuthUsersOne)
	t.Run("GooseDBVersions", testGooseDBVersionsOne)
	t.Run("Tokens", testTokensOne)
}

func TestAll(t *testing.T) {
	t.Run("AuthUsers", testAuthUsersAll)
	t.Run("GooseDBVersions", testGooseDBVersionsAll)
	t.Run("Tokens", testTokensAll)
}

func TestCount(t *testing.T) {
	t.Run("AuthUsers", testAuthUsersCount)
	t.Run("GooseDBVersions", testGooseDBVersionsCount)
	t.Run("Tokens", testTokensCount)
}

func TestHooks(t *testing.T) {
	t.Run("AuthUsers", testAuthUsersHooks)
	t.Run("GooseDBVersions", testGooseDBVersionsHooks)
	t.Run("Tokens", testTokensHooks)
}

func TestInsert(t *testing.T) {
	t.Run("AuthUsers", testAuthUsersInsert)
	t.Run("AuthUsers", testAuthUsersInsertWhitelist)
	t.Run("GooseDBVersions", testGooseDBVersionsInsert)
	t.Run("GooseDBVersions", testGooseDBVersionsInsertWhitelist)
	t.Run("Tokens", testTokensInsert)
	t.Run("Tokens", testTokensInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("AuthUsers", testAuthUsersReload)
	t.Run("GooseDBVersions", testGooseDBVersionsReload)
	t.Run("Tokens", testTokensReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("AuthUsers", testAuthUsersReloadAll)
	t.Run("GooseDBVersions", testGooseDBVersionsReloadAll)
	t.Run("Tokens", testTokensReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("AuthUsers", testAuthUsersSelect)
	t.Run("GooseDBVersions", testGooseDBVersionsSelect)
	t.Run("Tokens", testTokensSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("AuthUsers", testAuthUsersUpdate)
	t.Run("GooseDBVersions", testGooseDBVersionsUpdate)
	t.Run("Tokens", testTokensUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("AuthUsers", testAuthUsersSliceUpdateAll)
	t.Run("GooseDBVersions", testGooseDBVersionsSliceUpdateAll)
	t.Run("Tokens", testTokensSliceUpdateAll)
}
