apiVersion: v1
kind: Service
metadata:
  name: backend-main-service
  namespace: app-ns
spec:
  selector:
    app: backend-main
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
