apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-for-github-actions
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list" ]

  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "get", "create" ]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions
  namespace: app-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-for-github-actions
subjects:
  - kind: Group
    name: github-actions
    apiGroup: rbac.authorization.k8s.io