apiVersion: batch/v1
kind: Job
metadata:
  name: migration-backend-auth
  namespace: app-ns
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
        - name: migration-backend-auth
          image: __REGISTRY__/knowledge-backend-auth-migration:__IMAGE_TAG__
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: APP_ENV
      restartPolicy: OnFailure
