apiVersion: v1
kind: Service
metadata:
  name: backend-auth-service
  namespace: app-ns
spec:
  selector:
    app: backend-auth
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
