apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: KnowledgeCluster
  region: ap-northeast-1
  version: '1.30'
  tags:
    createdby: eksctl

nodeGroups:
  - name: EksctlNodegroups1
    instanceType: t3.small
    desiredCapacity: 1

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
    logRetentionInDays: 2