apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: KnowledgeCluster
  region: ap-northeast-1
  version: '1.29'
  tags:
    createdby: eksctl

nodeGroups:
  - name: EksctlNodegroups1
    instanceType: t3.small
    desiredCapacity: 1

accessConfig:
  authenticationMode: API
  accessEntries:
    - principalARN: arn:aws:iam::__AWS_ACCOUNT_ID__:role/github-oidc
      accessPolicies:
        - policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSEditPolicy
          accessScope:
            type: namespace
            namespaces:
              - app-ns
