pkgname = "db"
output  = "db"

[psql]
  dbname  = "knowledge-main-develop"
  host    = "localhost"
  port    = 5432
  user    = "postgres"
  pass    = "password"
  sslmode = "disable"
  blacklist = ["goose_db_version"]
