apiVersion: v1
kind: Service
metadata:
  name: sample-grpc-server-service
  namespace: app-ns
spec:
  selector:
    app: sample-grpc-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
