service: gha-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    GITHUB_TOKEN: ${env:GITHUB_TOKEN}

functions:
  gha-bot:
    handler: app.handler
    events:
      - httpApi:
          path: /slack/events
          method: post

plugins:
  - serverless-esbuild
  - serverless-offline
useDotenv: true
