// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

var TableNames = struct {
	Knowledges string
	Users      string
}{
	Knowledges: "knowledges",
	Users:      "users",
}
