// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Knowledges", testKnowledgesUpsert)

	t.Run("Users", testUsersUpsert)
}
