name: Batch | Backend Batch

on:
  workflow_dispatch:
    inputs:
      command:
        description: '実行コマンド名'
        required: true
      environment-name:
        type: environment # Environmentsを切り替え
        default: test
        required: false
        description: Environment name

env:
  REPOSITORY_NAME: knowledge-backend-batch
  CLUSTER_NAME: KnowledgeCluster

jobs:
  batch:
    name: ${{ inputs.environment-name }} | ${{ github.event.inputs.command }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }} # 利用するEnvironmentsを指定
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-oidc

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          images: |
            ${{ env.ECR_REGISTRY }}/${{ env.REPOSITORY_NAME }}
          tags: |
            type=sha

      - name: Image Tag from meta
        id: image-tag
        run: |
          tag=$(echo "${{ steps.meta.outputs.tags }}" | cut -d ":" -f 2)
          echo "::set-output name=tag::$tag"

      - name: Check if image exists
        id: check-image
        env:
          IMAGE_TAG: ${{ steps.image-tag.outputs.tag }}
        run: |
          EXISTS=$(aws ecr describe-images --repository-name "${{ env.REPOSITORY_NAME }}" --image-ids imageTag="${{ env.IMAGE_TAG }}" --region ap-northeast-1)
          if [ $? == 0 ]; then
            echo "Image found: ${{ env.IMAGE_TAG }}"
          else
            echo "::error::Image does not exist. Stopping workflow."
            exit 1
          fi

      - uses: azure/setup-kubectl@v4

      - name: Create kubeconfig file
        run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }}

      - name: Replace image tag in the Kubernetes deployment
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.image-tag.outputs.tag }}
        run: |
          echo "Input Command: ${{ github.event.inputs.command }}"
          sed 's/__IMAGE_TAG__/${{ env.IMAGE_TAG }}/g' ./backend/batch/k8s/exec-batch-job.yaml > /tmp/exec-batch-job.yaml
          sed -i 's/__REGISTRY__/${{ env.ECR_REGISTRY }}/g' /tmp/exec-batch-job.yaml
          # command にスラッシュが含まれるのでデリミタを#にする
          sed -i 's#__COMMAND__#${{ github.event.inputs.command }}#g' /tmp/exec-batch-job.yaml
          kubectl apply -f /tmp/exec-batch-job.yaml -n app-ns