name: CI | Backend Main
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: knowledge-main-test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        go: [ '1.20' ]
    defaults:
      run:
        working-directory: backend/main
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Check dependencies
        run: |
          go mod verify

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: backend/main

      - name: Migrate
        env:
          DB_HOST: localhost
          DB_PASSWORD: password
          DB_NAME: knowledge-main-test
        run: |
          make migration

      - name: Run test
        run: |
          go test -v -test.config=./sqlboiler.test.toml ./...

      - name: Install govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: |
          govulncheck ./...