name: CI | Frontend Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.5.1]

    defaults:
      run:
        working-directory: frontend/main
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./frontend/main/package-lock.json

      - name: Check Cache Hit
        shell: bash
        run: |
          echo "cache-hit: ${{ steps.setup-node.outputs.cache-hit }}"

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm run test:ci

      - name: Build
        run: npm run build
