name: Push Image Migration (Main)

on:
  workflow_dispatch:
  repository_dispatch:
    types: [push-image-migration]

env:
  REPOSITORY_NAME: knowledge-backend-main-migration

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-oidc

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          images: |
            ${{ env.ECR_REGISTRY }}/${{ env.REPOSITORY_NAME }}
          tags: |
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/main/Dockerfile.migration
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
